# Generated by Django 6.0.3 on 2026-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_review_created_at_remove_serviceorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
