# Generated by Django 6.0.3 on 2026-03-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_category_alter_resume_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='professian',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
