# Generated by Django 6.0.3 on 2026-03-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_resume_professian'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
