# Generated by Django 6.0.3 on 2026-03-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_resume_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('user_text', models.TextField()),
                ('mode', models.CharField(choices=[('summary', 'Summary'), ('quiz', 'Quiz'), ('keywords', 'Keywords'), ('simplify', 'Simplify'), ('ask', 'Ask')], max_length=20)),
                ('ai_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
