# Generated by Django 6.0.3 on 2026-03-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_airequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
