# Generated by Django 6.0.3 on 2026-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_airequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
