# Generated by Django 6.0.3 on 2026-04-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_airequest_ai_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='duration_unit',
            field=models.CharField(choices=[('hours', 'Часы'), ('days', 'Дни')], default='hours', max_length=10),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='duration_value',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
